### ISSUE TITLE
SIM800L disconnects

### ISSUE THREAD

**Issue by kylix34** [hologram-io/hologram-SIM800#9]
Hello,

I'm doind some tests with SIM800L module, sending it commands from the Hologram Console.
The problem is that after some time, the module disconnects from the internet and doesn't answer anymore to the commands send through the console (it still remains connected to the 2G network but the internet connection drops). 
Is there any way to keep the internet connection always "ON"?

**Comment by kylix34** [comment]
In the meanwhile I updated the firmware to the latest available version on the SiteCom's website. Hope it solves the issue.

PS: updating the firmware didn't help ....

**Comment by benstr** [comment]
This is the intended behavior on the carrier level. Cell towers have a limit to the number of devices that can connect. After some duration of inactivity, the tower will automatically drop the device. Device side firmware should take this into consideration by checking connection and reconnecting as needed.

**Comment by kylix34** [comment]
Any example on how to check the connection status in the loop and reconnect if disconnected?
